###################
# local
###################
server.port: 18080

spring:
  datasource:
    url: jdbc:postgresql://hanex-dev-rds-temp-708b1e60bce84582.elb.ap-northeast-2.amazonaws.com:5432/hanexdb
    driverClassName: org.postgresql.Driver
    username: hanexuser
    password: hanex1234!!
    # driver-class-name: org.h2.Driver
    # username: sa
    # password:
    # url: jdbc:h2:mem:starter;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    #initialization-mode: always
    #schema: classpath:schema-h2.sql
    #data: classpath:data-h2.sql
  h2:
    console.enabled: true
  redis:
    #host: host.docker.internal
    host: localhost
    port: 6001

logging:
  config: classpath:log4j2-local.xml