###################
# dev
###################

server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://192.168.41.50:5432/openmsadb
    driverClassName: org.postgresql.Driver
    username: openmsauser
    password: open1234!!
  redis:
    host: localhost
    port: 6001

logging:
  config: classpath:log4j2-dev.xml

